// <auto-generated />
using System;
using MesEnterprise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MesEnterprise.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20251117141009_AdaugaEvaluationWindowMinutesLaAlertRule")]
    partial class AdaugaEvaluationWindowMinutesLaAlertRule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MesEnterprise.Models.Alerts.AlertLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("alert_rule_id");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledged");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_log");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("ix_alert_log_alert_rule_id");

                    b.HasIndex("TriggeredAt", "AlertRuleId")
                        .HasDatabaseName("ix_alert_log_triggered_at_alert_rule_id");

                    b.ToTable("alert_log", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Alerts.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EvaluationWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_window_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("RuleConfiguration")
                        .HasColumnType("text")
                        .HasColumnName("rule_configuration");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<int>("ThresholdValue")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_value");

                    b.HasKey("Id")
                        .HasName("pk_alert_rule");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_alert_rule_line_id");

                    b.ToTable("alert_rule", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Config.StopOnDefectRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<int>("MaxConsecutiveNRFT")
                        .HasColumnType("integer")
                        .HasColumnName("max_consecutive_nrft");

                    b.Property<int>("MaxConsecutiveScrap")
                        .HasColumnType("integer")
                        .HasColumnName("max_consecutive_scrap");

                    b.Property<int>("MaxNrftPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("max_nrft_per_hour");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_stop_on_defect_rule");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_stop_on_defect_rule_line_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stop_on_defect_rule_product_id");

                    b.ToTable("stop_on_defect_rule", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Config.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_system_setting");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_setting_key");

                    b.ToTable("system_setting", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.BreakdownReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_breakdown_reason");

                    b.ToTable("breakdown_reason", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_maintenance_date");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("OreFunctionare")
                        .HasColumnType("numeric")
                        .HasColumnName("ore_functionare");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_equipment_line_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostOperarePeOra")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_operare_pe_ora");

                    b.Property<string>("DataAcquisitionMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_acquisition_mode");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<bool>("HasLiveScanning")
                        .HasColumnType("boolean")
                        .HasColumnName("has_live_scanning");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ScanIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scan_identifier");

                    b.HasKey("Id")
                        .HasName("pk_line");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_line_department_id");

                    b.HasIndex("ScanIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_line_scan_identifier");

                    b.ToTable("line", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.ObservatieOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ora");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_observatie_operator");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_observatie_operator_line_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_observatie_operator_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_observatie_operator_user_id");

                    b.ToTable("observatie_operator", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.PlannedDowntime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<double>("MinutesPerHour")
                        .HasColumnType("double precision")
                        .HasColumnName("minutes_per_hour");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_planned_downtime");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_planned_downtime_product_id");

                    b.HasIndex("LineId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_downtime_line_id_product_id");

                    b.ToTable("planned_downtime", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("CycleTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("cycle_time_seconds");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shift");

                    b.ToTable("shift", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.ShiftBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BreakTime")
                        .HasColumnType("interval")
                        .HasColumnName("break_time");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_break");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_shift_break_shift_id");

                    b.ToTable("shift_break", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Export.ExportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QueryConfiguration")
                        .HasColumnType("text")
                        .HasColumnName("query_configuration");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_export_job");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_export_job_created_by_user_id");

                    b.ToTable("export_job", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Export.ExportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_type");

                    b.HasKey("Id")
                        .HasName("pk_export_template");

                    b.ToTable("export_template", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Inventory.ProductBOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_per_unit");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("raw_material_id");

                    b.HasKey("Id")
                        .HasName("pk_product_bom");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_bom_product_id");

                    b.HasIndex("RawMaterialId")
                        .HasDatabaseName("ix_product_bom_raw_material_id");

                    b.ToTable("product_bom", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Inventory.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_code");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_in_stock");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_raw_material");

                    b.ToTable("raw_material", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Inventory.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_spare_part");

                    b.ToTable("spare_part", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.DefectiuneIdentificata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nume");

                    b.HasKey("Id")
                        .HasName("pk_defectiune_identificata");

                    b.ToTable("defectiune_identificata", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.InterventieTichet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CAPADueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capa_due_date");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("text")
                        .HasColumnName("corrective_action");

                    b.Property<decimal?>("CostManopera")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_manopera");

                    b.Property<decimal?>("CostPiese")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_piese");

                    b.Property<DateTime>("DataRaportareOperator")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_raportare_operator");

                    b.Property<DateTime?>("DataStartInterventie")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_start_interventie");

                    b.Property<DateTime?>("DataStopInterventie")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_stop_interventie");

                    b.Property<int?>("DefectiuneIdentificataId")
                        .HasColumnType("integer")
                        .HasColumnName("defectiune_identificata_id");

                    b.Property<string>("DefectiuneTextLiber")
                        .HasColumnType("text")
                        .HasColumnName("defectiune_text_liber");

                    b.Property<int?>("DurataMinute")
                        .HasColumnType("integer")
                        .HasColumnName("durata_minute");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("InfluenteazaProdusul")
                        .HasColumnType("boolean")
                        .HasColumnName("influenteaza_produsul");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("OperatorNume")
                        .HasColumnType("text")
                        .HasColumnName("operator_nume");

                    b.Property<string>("PreventiveAction")
                        .HasColumnType("text")
                        .HasColumnName("preventive_action");

                    b.Property<int?>("ProblemaRaportataId")
                        .HasColumnType("integer")
                        .HasColumnName("problema_raportata_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("RootCause")
                        .HasColumnType("text")
                        .HasColumnName("root_cause");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TehnicianNume")
                        .HasColumnType("text")
                        .HasColumnName("tehnician_nume");

                    b.Property<Guid>("UnicIdTicket")
                        .HasColumnType("uuid")
                        .HasColumnName("unic_id_ticket");

                    b.HasKey("Id")
                        .HasName("pk_interventie_tichet");

                    b.HasIndex("DefectiuneIdentificataId")
                        .HasDatabaseName("ix_interventie_tichet_defectiune_identificata_id");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_interventie_tichet_equipment_id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_interventie_tichet_line_id");

                    b.HasIndex("ProblemaRaportataId")
                        .HasDatabaseName("ix_interventie_tichet_problema_raportata_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_interventie_tichet_product_id");

                    b.HasIndex("UnicIdTicket")
                        .IsUnique()
                        .HasDatabaseName("ix_interventie_tichet_unic_id_ticket");

                    b.HasIndex("Status", "DataRaportareOperator")
                        .HasDatabaseName("ix_interventie_tichet_status_data_raportare_operator");

                    b.ToTable("interventie_tichet", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.PreventiveMaintenancePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequency");

                    b.Property<int>("FrequencyValue")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastExecutedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_executed_date");

                    b.Property<int?>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text")
                        .HasColumnName("task_description");

                    b.HasKey("Id")
                        .HasName("pk_preventive_maintenance_plan");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_preventive_maintenance_plan_equipment_id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_preventive_maintenance_plan_line_id");

                    b.ToTable("preventive_maintenance_plan", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.ProblemaDefectiuneCorelatie", b =>
                {
                    b.Property<int>("ProblemaRaportataId")
                        .HasColumnType("integer")
                        .HasColumnName("problema_raportata_id");

                    b.Property<int>("DefectiuneIdentificataId")
                        .HasColumnType("integer")
                        .HasColumnName("defectiune_identificata_id");

                    b.HasKey("ProblemaRaportataId", "DefectiuneIdentificataId")
                        .HasName("pk_problema_defectiune_corelatie");

                    b.HasIndex("DefectiuneIdentificataId")
                        .HasDatabaseName("ix_problema_defectiune_corelatie_defectiune_identificata_id");

                    b.ToTable("problema_defectiune_corelatie", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.ProblemaRaportata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nume");

                    b.HasKey("Id")
                        .HasName("pk_problema_raportata");

                    b.ToTable("problema_raportata", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Planning.ProductionWorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_date");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end_date");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start_date");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("produced_quantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("work_order_number");

                    b.HasKey("Id")
                        .HasName("pk_production_work_order");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_production_work_order_line_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_work_order_product_id");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_production_work_order_work_order_number");

                    b.ToTable("production_work_order", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ChangeoverLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<int>("ProductFromId")
                        .HasColumnType("integer")
                        .HasColumnName("product_from_id");

                    b.Property<int>("ProductToId")
                        .HasColumnType("integer")
                        .HasColumnName("product_to_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_changeover_log");

                    b.HasIndex("ProductFromId")
                        .HasDatabaseName("ix_changeover_log_product_from_id");

                    b.HasIndex("ProductToId")
                        .HasDatabaseName("ix_changeover_log_product_to_id");

                    b.HasIndex("LineId", "StartTime")
                        .HasDatabaseName("ix_changeover_log_line_id_start_time");

                    b.ToTable("changeover_log", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.LineStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("current_shift_id");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_change");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_line_status");

                    b.HasIndex("CurrentShiftId")
                        .HasDatabaseName("ix_line_status_current_shift_id");

                    b.HasIndex("LineId")
                        .IsUnique()
                        .HasDatabaseName("ix_line_status_line_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_line_status_product_id");

                    b.ToTable("line_status", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ProductionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualParts")
                        .HasColumnType("integer")
                        .HasColumnName("actual_parts");

                    b.Property<int?>("DeclaredDowntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("declared_downtime_minutes");

                    b.Property<int?>("DeclaredDowntimeReasonId")
                        .HasColumnType("integer")
                        .HasColumnName("declared_downtime_reason_id");

                    b.Property<string>("HourInterval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hour_interval");

                    b.Property<string>("JustificationReason")
                        .HasColumnType("text")
                        .HasColumnName("justification_reason");

                    b.Property<bool>("JustificationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("justification_required");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<int>("NrftParts")
                        .HasColumnType("integer")
                        .HasColumnName("nrft_parts");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionWorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("production_work_order_id");

                    b.Property<int>("ScrapParts")
                        .HasColumnType("integer")
                        .HasColumnName("scrap_parts");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<int?>("SystemStopMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("system_stop_minutes");

                    b.Property<int>("TargetParts")
                        .HasColumnType("integer")
                        .HasColumnName("target_parts");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_production_log");

                    b.HasIndex("DeclaredDowntimeReasonId")
                        .HasDatabaseName("ix_production_log_declared_downtime_reason_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_log_product_id");

                    b.HasIndex("ProductionWorkOrderId")
                        .HasDatabaseName("ix_production_log_production_work_order_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_production_log_shift_id");

                    b.HasIndex("LineId", "Timestamp")
                        .HasDatabaseName("ix_production_log_line_id_timestamp");

                    b.ToTable("production_log", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ProductionLogDefect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("defect_code_id");

                    b.Property<int>("ProductionLogId")
                        .HasColumnType("integer")
                        .HasColumnName("production_log_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_production_log_defect");

                    b.HasIndex("DefectCodeId")
                        .HasDatabaseName("ix_production_log_defect_defect_code_id");

                    b.HasIndex("ProductionLogId")
                        .HasDatabaseName("ix_production_log_defect_production_log_id");

                    b.ToTable("production_log_defect", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.DefectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_defect_category");

                    b.ToTable("defect_category", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.DefectCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefectCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("defect_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_defect_code");

                    b.HasIndex("DefectCategoryId")
                        .HasDatabaseName("ix_defect_code_defect_category_id");

                    b.ToTable("defect_code", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.MrbTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefectDescription")
                        .HasColumnType("text")
                        .HasColumnName("defect_description");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("defective_quantity");

                    b.Property<string>("Disposition")
                        .HasColumnType("text")
                        .HasColumnName("disposition");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionLogId")
                        .HasColumnType("integer")
                        .HasColumnName("production_log_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_number");

                    b.HasKey("Id")
                        .HasName("pk_mrb_ticket");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_mrb_ticket_product_id");

                    b.HasIndex("ProductionLogId")
                        .HasDatabaseName("ix_mrb_ticket_production_log_id");

                    b.ToTable("mrb_ticket", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.ProductionLogQualityCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductionLogId")
                        .HasColumnType("integer")
                        .HasColumnName("production_log_id");

                    b.Property<int>("QualityTestId")
                        .HasColumnType("integer")
                        .HasColumnName("quality_test_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<DateTime>("TestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tested_at");

                    b.HasKey("Id")
                        .HasName("pk_production_log_quality_check");

                    b.HasIndex("ProductionLogId")
                        .HasDatabaseName("ix_production_log_quality_check_production_log_id");

                    b.HasIndex("QualityTestId")
                        .HasDatabaseName("ix_production_log_quality_check_quality_test_id");

                    b.ToTable("production_log_quality_check", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.QualityTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("text")
                        .HasColumnName("acceptance_criteria");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("test_type");

                    b.HasKey("Id")
                        .HasName("pk_quality_test");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_quality_test_product_id");

                    b.ToTable("quality_test", (string)null);
                });

            modelBuilder.Entity("MesEnterprise.Models.Alerts.AlertLog", b =>
                {
                    b.HasOne("MesEnterprise.Models.Alerts.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .HasConstraintName("fk_alert_log_alert_rule_alert_rule_id");

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("MesEnterprise.Models.Alerts.AlertRule", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .HasConstraintName("fk_alert_rule_line_line_id");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("MesEnterprise.Models.Config.StopOnDefectRule", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stop_on_defect_rule_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_stop_on_defect_rule_product_product_id");

                    b.Navigation("Line");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Equipment", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany("Equipments")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_line_line_id");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Line", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Department", "Department")
                        .WithMany("Lines")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_line_department_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.ObservatieOperator", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observatie_operator_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observatie_operator_product_product_id");

                    b.HasOne("MesEnterprise.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_observatie_operator_user_user_id");

                    b.Navigation("Line");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.PlannedDowntime", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_downtime_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_downtime_product_product_id");

                    b.Navigation("Line");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.RolePermission", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("MesEnterprise.Models.Core.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.ShiftBreak", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Shift", "Shift")
                        .WithMany("Breaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_break_shift_shift_id");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.User", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_user_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MesEnterprise.Models.Export.ExportJob", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("fk_export_job_user_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MesEnterprise.Models.Inventory.ProductBOM", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_bom_product_product_id");

                    b.HasOne("MesEnterprise.Models.Inventory.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_bom_raw_material_raw_material_id");

                    b.Navigation("Product");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.InterventieTichet", b =>
                {
                    b.HasOne("MesEnterprise.Models.Maintenance.DefectiuneIdentificata", "DefectiuneIdentificata")
                        .WithMany()
                        .HasForeignKey("DefectiuneIdentificataId")
                        .HasConstraintName("fk_interventie_tichet_defectiune_identificata_defectiune_ident");

                    b.HasOne("MesEnterprise.Models.Core.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interventie_tichet_equipment_equipment_id");

                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interventie_tichet_line_line_id");

                    b.HasOne("MesEnterprise.Models.Maintenance.ProblemaRaportata", "ProblemaRaportata")
                        .WithMany()
                        .HasForeignKey("ProblemaRaportataId")
                        .HasConstraintName("fk_interventie_tichet_problema_raportata_problema_raportata_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_interventie_tichet_product_product_id");

                    b.Navigation("DefectiuneIdentificata");

                    b.Navigation("Equipment");

                    b.Navigation("Line");

                    b.Navigation("ProblemaRaportata");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.PreventiveMaintenancePlan", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("fk_preventive_maintenance_plan_equipment_equipment_id");

                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .HasConstraintName("fk_preventive_maintenance_plan_line_line_id");

                    b.Navigation("Equipment");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.ProblemaDefectiuneCorelatie", b =>
                {
                    b.HasOne("MesEnterprise.Models.Maintenance.DefectiuneIdentificata", "DefectiuneIdentificata")
                        .WithMany("Corelatii")
                        .HasForeignKey("DefectiuneIdentificataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problema_defectiune_corelatie_defectiune_identificata_defec");

                    b.HasOne("MesEnterprise.Models.Maintenance.ProblemaRaportata", "ProblemaRaportata")
                        .WithMany("Corelatii")
                        .HasForeignKey("ProblemaRaportataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problema_defectiune_corelatie_problema_raportata_problema_r");

                    b.Navigation("DefectiuneIdentificata");

                    b.Navigation("ProblemaRaportata");
                });

            modelBuilder.Entity("MesEnterprise.Models.Planning.ProductionWorkOrder", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_work_order_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_work_order_product_product_id");

                    b.Navigation("Line");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ChangeoverLog", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_changeover_log_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "ProductFrom")
                        .WithMany()
                        .HasForeignKey("ProductFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_changeover_log_product_product_from_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "ProductTo")
                        .WithMany()
                        .HasForeignKey("ProductToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_changeover_log_product_product_to_id");

                    b.Navigation("Line");

                    b.Navigation("ProductFrom");

                    b.Navigation("ProductTo");
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.LineStatus", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Shift", "CurrentShift")
                        .WithMany()
                        .HasForeignKey("CurrentShiftId")
                        .HasConstraintName("fk_line_status_shift_current_shift_id");

                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_status_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_line_status_product_product_id");

                    b.Navigation("CurrentShift");

                    b.Navigation("Line");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ProductionLog", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.BreakdownReason", "DeclaredDowntimeReason")
                        .WithMany()
                        .HasForeignKey("DeclaredDowntimeReasonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_production_log_breakdown_reason_declared_downtime_reason_id");

                    b.HasOne("MesEnterprise.Models.Core.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_line_line_id");

                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_product_product_id");

                    b.HasOne("MesEnterprise.Models.Planning.ProductionWorkOrder", "ProductionWorkOrder")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("ProductionWorkOrderId")
                        .HasConstraintName("fk_production_log_production_work_order_production_work_order_");

                    b.HasOne("MesEnterprise.Models.Core.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_shift_shift_id");

                    b.Navigation("DeclaredDowntimeReason");

                    b.Navigation("Line");

                    b.Navigation("Product");

                    b.Navigation("ProductionWorkOrder");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ProductionLogDefect", b =>
                {
                    b.HasOne("MesEnterprise.Models.Quality.DefectCode", "DefectCode")
                        .WithMany()
                        .HasForeignKey("DefectCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_defect_defect_code_defect_code_id");

                    b.HasOne("MesEnterprise.Models.Production.ProductionLog", "ProductionLog")
                        .WithMany("DefectAllocations")
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_defect_production_log_production_log_id");

                    b.Navigation("DefectCode");

                    b.Navigation("ProductionLog");
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.DefectCode", b =>
                {
                    b.HasOne("MesEnterprise.Models.Quality.DefectCategory", "Category")
                        .WithMany("DefectCodes")
                        .HasForeignKey("DefectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defect_code_defect_category_defect_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.MrbTicket", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mrb_ticket_product_product_id");

                    b.HasOne("MesEnterprise.Models.Production.ProductionLog", "ProductionLog")
                        .WithMany()
                        .HasForeignKey("ProductionLogId")
                        .HasConstraintName("fk_mrb_ticket_production_log_production_log_id");

                    b.Navigation("Product");

                    b.Navigation("ProductionLog");
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.ProductionLogQualityCheck", b =>
                {
                    b.HasOne("MesEnterprise.Models.Production.ProductionLog", "ProductionLog")
                        .WithMany()
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_quality_check_production_log_production_log_");

                    b.HasOne("MesEnterprise.Models.Quality.QualityTest", "QualityTest")
                        .WithMany()
                        .HasForeignKey("QualityTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_log_quality_check_quality_test_quality_test_id");

                    b.Navigation("ProductionLog");

                    b.Navigation("QualityTest");
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.QualityTest", b =>
                {
                    b.HasOne("MesEnterprise.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_quality_test_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Department", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Line", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MesEnterprise.Models.Core.Shift", b =>
                {
                    b.Navigation("Breaks");
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.DefectiuneIdentificata", b =>
                {
                    b.Navigation("Corelatii");
                });

            modelBuilder.Entity("MesEnterprise.Models.Maintenance.ProblemaRaportata", b =>
                {
                    b.Navigation("Corelatii");
                });

            modelBuilder.Entity("MesEnterprise.Models.Planning.ProductionWorkOrder", b =>
                {
                    b.Navigation("ProductionLogs");
                });

            modelBuilder.Entity("MesEnterprise.Models.Production.ProductionLog", b =>
                {
                    b.Navigation("DefectAllocations");
                });

            modelBuilder.Entity("MesEnterprise.Models.Quality.DefectCategory", b =>
                {
                    b.Navigation("DefectCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
